import math 
# or you can do as
# from math import sqrt

# now you don't need to write math.sqrt()
#                       just sqrt() is fine
                      
# and import math as m

# or just to import every function from math individually you can do as
   
#    "from math import *"
   
# to check all the function available in maths just do

# print(dir(math))

# we are also able to print the class and type of the library bieng imported

# from  error404 import test_code, funpy
# test_code()
# print(funpy)

import error404 as er4
er4.test_code()
print(er4.funpy)