#BEFORE PYTHON 3.6 
into = "hey do you have a big {} and a large {}"

num = "house" 
poa = "latte"

print(into.format(num, poa))

#INCONVINIENT 

#SO THERE IS A NEW WAY TO DO THIS IN PYTHON 3.6 AND ABOVE 



print(f"hey do you have a big {num} and a large {poa}")
PRICE = 1000.99999999986
prt = f"FOR ONLY{PRICE:.3f} rupees"
print(prt)
'''print(prt.format())'''
#THIS IS THE NEW WAY TO DO THIS IN PYTHON 3.6 AND ABOVE
print("{2*30}")
print(f"{2*30}")
#THIS IS THE NEW WAY TO DO THIS IN PYTHON 3.6 AND ABOVE
print(f"hey do you have a big {{num}} and a large {{poa}}")
#THIS IS THE NEW WAY TO DO THIS IN PYTHON 3.6 AND ABOVE